#!/bin/sh

# Simple change dirs and compile projects
# Makefile containes moving to system bin 

set -e

PROGRAMS=("dmenu" "dwm" "slstatus" "st")


echo "Starting programs..."

for dir in "${PROGRAMS[@]}"
do
    if [ -d "$dir" ]
    then
        echo "Installing $dir..."
        cd "$dir"
        sudo make install clean
        cd ..
        echo "Installed $dir"
    else
        echo "$dir does not exist"
    fi
done

echo "Done!"
