#!/bin/bash

set -e

DEFAULT_PATH="$HOME/Downloads/Git/wm-dotfiles"
LINKS_PATH="$DEFAULT_PATH"

# Use this path after creating links
TPM_PATH="$HOME/.tmux/plugins/tpm"
GIT_TPM_PATH="https://github.com/tmux-plugins/tpm"

if [[ -d "$TPM_PATH" ]]
then
    # -f for a git non-empty directory
    rm -rf "$TPM_PATH"
else 
    mkdir -p "$TPM_PATH"
fi

if [ -z "$1" ]
then
    read -p "Do you want to use default path ($DEFAULT_PATH) y/n? " ans1
    if [[ !"$ans1" = "y" ]]
    then 
        echo "Provide path to linking files"
        echo "Example:"
        echo "  ./setup-tmux $DEFAULT_PATH"
        exit 1
    fi
else 
    LINKS_PATH=$1
fi


echo "Linking config files..."

read -p "Create .bak files? (y/n) " ans2

if [[ "$ans2" = "y" ]]
then
    echo "Backing up all files"
else
    echo "Skip backing up the old files, only delete"
fi

LINKS=(
    "$LINKS_PATH/.tmux.conf:$HOME/.tmux.conf"
    # "$LINKS_PATH/.tmux:$HOME/.tmux"
)

for link in "${LINKS[@]}"; do
    src=$(echo "$link" | cut -d ':' -f 1)
    dst=$(echo "$link" | cut -d ':' -f 2)

    mkdir -p "$(dirname "$dst")"

    if [ -f "$dst" ] || [ -L "$dst" ]; then
        if [[ "$ans2" = "y" ]]
        then
            mv "$dst" "${dst}.bak"
        else
            rm "$dst"
        fi
    fi

    ln -s "$src" "$dst"
    echo "Linked $src -> $dst"
done

echo "Downloading tpm..."

git clone "$GIT_TPM_PATH" "$TPM_PATH"

echo "Done!"
